name: climbr_dart
description: Climbr - web app for climbers
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.0.0
  angular2_components: ^0.1.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  intl: any
  firebase3: ^0.2.1
  ng_bootstrap: any
  sass_transformer: any
transformers:
- sass_transformer
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter