name: climbr_dart
description: Climbr - web app for climbers
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.0.0
  angular2_components: ^0.1.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  intl: any
  firebase3: ^0.2.1
  polymer: ^1.0.0-rc.18
  polymer_elements: ^1.0.0-rc.9
  web_components: ^0.12.0
transformers:
- polymer:
    entry_points: web/index.html
- angular2: 
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives